# Generated by Django 4.0.4 on 2022-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_cep_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cep',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cep',
            name='nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
