# Generated by Django 4.0.4 on 2022-06-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_cep_email_cep_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cep',
            name='descricao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
